### ISSUE TITLE
[docker] CRITICAL:pip.subprocessor:Error [Errno 2] No such file or directory: 'git'

### ISSUE THREAD

**Issue by a-w11** [jantman/awslimitchecker#471]
Hello,

I have issue with docker-compose stack, after few errors in logs container is going to restarting state.

docker-compose:
```
version: "3.3"
services:
  monitor:
    image: jantman/awslimitchecker
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    logging:
      driver: json-file
      options:
        max-size: "100M"
        max-file: "5"
```

Log:
```
monitor_1  | CRITICAL:pip.subprocessor:Error [Errno 2] No such file or directory: 'git' while executing command git config --get-regexp 'remote\..*\.url'
monitor_1  | awslimitchecker 8.0.2 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
monitor_1  | WARNING:awslimitchecker.trustedadvisor:Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
```
